workflows:
  default-workflow:
    name: iOS Unsigned Build (AltStore)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS Runner.app
        script: |
          # Install pods first
          cd ios && pod install && cd ..
          
          # Build using xcodebuild directly to override signing settings
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build/ios \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Package IPA
        script: |
          # Path adjustment for direct xcodebuild output
          cd build/ios/Build/Products/Release-iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r Runner.ipa Payload
          mv Runner.ipa ../../../../../Runner.ipa
    artifacts:
      - Runner.ipa
