workflows:
  default-workflow:
    name: iOS Unsigned Build (AltStore)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install Pods
        script: |
          cd ios && pod install && cd ..
      - name: Build iOS Runner.app
        script: |
          # Build unsigned release with explicit overrides to bypass signing checks
          flutter build ios --release --no-codesign -- CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM="" PROVISIONING_PROFILE_SPECIFIER=""
      - name: Package IPA
        script: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r Runner.ipa Payload
          mv Runner.ipa ../../../Runner.ipa
    artifacts:
      - Runner.ipa
